In [ ]:
# Name: Raghav Sharma
# Roll No: 25201313

In [ ]:
# Tensorflow & Pytorch

In [ ]:
# A) 1) Perform element wise addition on two tensors a and b and print the result

In [ ]:
# TensorFlow: Element-wise Addition

In [ ]:
import tensorflow as tf

# Define tensors
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

# Element-wise addition
result = a + b

print(result)


tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [ ]:
# PyTorch: Element-wise Addition

In [ ]:
import torch

# Define tensors
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# Element-wise addition
result = a + b

print(result)


tensor([5, 7, 9])


In [ ]:
# 2) Multiply two tensors element wise

In [ ]:
# TensorFlow: Element-wise Multiplication

In [ ]:
import tensorflow as tf

# Define tensors
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

# Element-wise multiplication
result = a * b

print(result)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [ ]:
# PyTorch: Element-wise Multiplication

In [ ]:
import torch

# Define tensors
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# Element-wise multiplication
result = a * b

print(result)


tensor([ 4, 10, 18])


In [ ]:
# B)create  a dense layer with 128 units and Relu activation function.

In [ ]:
# TensorFlow (Keras)

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

# Create Dense layer
dense_layer = Dense(128, activation='relu')

# Example usage with input tensor
x = tf.random.normal((1, 64))  # batch_size=1, input_features=64
y = dense_layer(x)

print(y.shape)


(1, 128)


In [ ]:
# PyTorch

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# Create Dense (Linear) layer
dense_layer = nn.Linear(64, 128)  # input_features=64, output_features=128

# Example usage with input tensor
x = torch.randn(1, 64)

# Apply ReLU activation
y = F.relu(dense_layer(x))

print(y.shape)


torch.Size([1, 128])


In [ ]:
# C) 1) Build a sequential model with 2 dense layers, one with 256 units and another with 10 units which is the output layer.


In [ ]:
# TensorFlow (Keras Sequential API)

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Build Sequential model
model = Sequential([
    Dense(256, activation='relu', input_shape=(64,)),  # hidden layer
    Dense(10)                                           # output layer
])

# Model summary
model.summary()


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 256)            │        16,640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 10)             │         2,570 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 19,210 (75.04 KB)

 Trainable params: 19,210 (75.04 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# PyTorch (Sequential)

In [ ]:
import torch
import torch.nn as nn

# Build Sequential model
model = nn.Sequential(
    nn.Linear(64, 256),  # hidden layer
    nn.ReLU(),
    nn.Linear(256, 10)   # output layer
)

# Example forward pass
x = torch.randn(1, 64)
y = model(x)

print(y.shape)


torch.Size([1, 10])


In [ ]:
# 2) Compile, train, using Adam Optimiser and sparse categorical cross entropy loss over 10 epochs, with a batch size of 32. You have to save th model with (my_) any name and then we have to load the model

In [ ]:
# TensorFlow (Keras)

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

# Build the model
model = Sequential([
    Dense(256, activation='relu', input_shape=(64,)),
    Dense(10)   # output layer
])

# Compile the model
model.compile(
    optimizer=Adam(),
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=['accuracy']
)

# Dummy training data (for Colab demo)
X_train = tf.random.normal((1000, 64))
y_train = tf.random.uniform((1000,), minval=0, maxval=10, dtype=tf.int32)

# Train the model
model.fit(
    X_train,
    y_train,
    epochs=10,
    batch_size=32
)

# Save the model
model.save("/content/my_model.keras")

from tensorflow.keras.models import load_model

loaded_model = load_model("/content/my_model.keras")
print("Model loaded successfully!")




Epoch 1/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0938 - loss: 2.4285
Epoch 2/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2128 - loss: 2.1717
Epoch 3/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3227 - loss: 2.0429
Epoch 4/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3825 - loss: 1.9277
Epoch 5/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4401 - loss: 1.8187
Epoch 6/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4702 - loss: 1.7286
Epoch 7/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5140 - loss: 1.6589
Epoch 8/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5521 - loss: 1.5777
Epoch 9/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6144 - loss: 1.4771
Epoch 10/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6170 - loss: 1.4435
Model loaded successfully!


In [ ]:
# PyTorch

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

# Define model
model = nn.Sequential(
    nn.Linear(64, 256),
    nn.ReLU(),
    nn.Linear(256, 10)
)

# Loss & optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters())

# Dummy training data
X_train = torch.randn(1000, 64)
y_train = torch.randint(0, 10, (1000,))

dataset = TensorDataset(X_train, y_train)
loader = DataLoader(dataset, batch_size=32, shuffle=True)

# Training loop
for epoch in range(10):
    for x_batch, y_batch in loader:
        optimizer.zero_grad()
        outputs = model(x_batch)
        loss = criterion(outputs, y_batch)
        loss.backward()
        optimizer.step()
    print(f"Epoch {epoch+1}/10 completed")

# Save model
torch.save(model.state_dict(), "my_model.pth")

# Load model
loaded_model = nn.Sequential(
    nn.Linear(64, 256),
    nn.ReLU(),
    nn.Linear(256, 10)
)
loaded_model.load_state_dict(torch.load("my_model.pth"))
loaded_model.eval()

print("Model saved and loaded successfully!")


Epoch 1/10 completed
Epoch 2/10 completed
Epoch 3/10 completed
Epoch 4/10 completed
Epoch 5/10 completed
Epoch 6/10 completed
Epoch 7/10 completed
Epoch 8/10 completed
Epoch 9/10 completed
Epoch 10/10 completed
Model saved and loaded successfully!


In [ ]:
# Keras

In [ ]:
# 1) Define a 2 layer sequential model, compile it, & run for 30 epochs, & print the predicted results.
# X1 = [1,2,3,4]
# Y1 = [2,4,6,8]
# Y = 2X
# Linear model

In [40]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Data
X1 = np.array([1, 2, 3, 4])
Y1 = np.array([2, 4, 6, 8])

# Define a 2-layer Sequential model
model = Sequential([
    Dense(1, input_shape=(1,), activation='linear'),  # Layer 1
    Dense(1, activation='linear')                      # Layer 2
])

# Compile the model
model.compile(
    optimizer='adam',
    loss='mean_squared_error'
)

# Train the model
model.fit(X1, Y1, epochs=30, verbose=0)

# Predict
predictions = model.predict(X1)

# Print results
print("Input X:", X1)
print("Predicted Y:", predictions.flatten())


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
Input X: [1 2 3 4]
Predicted Y: [-1.8151743 -3.7024856 -5.589797  -7.4771085]
